# Server Configuration
server:
  port: 8081

# Spring Configuration
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-server: localhost:9092
    consumer:
      group-id: user-notification-group
      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: com.ust.processing_service.dto.OrderStatusEvent:com.ust.user_service.dto.OrderStatusEvent

user:
  kafka:
    topics:
      order-status: order-status-event

    groups:
      user-group: user-notification-group