spring:
  application:
    name: payment-service
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      acks: all
    consumer:
      group-id: payment-service-group
      auto-offset-reset: earliest

server:
  port: 8082

topics:
  email-topic: booking-confirmation-topic
  payment-topic: payment-json-topic

kind: Application
